version: '3.0'
services:
  web:
    image: pingwinno/twitch-o-matic
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - settings:/etc/streamarchive
      - path to storage:/root/streams
      - path to logs:/var/log/tom/
volumes:
  settings: